name: Python application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest

  Email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}} #smpt://SARANKUMAR G:mtbw vhhr wjax stsm@smtp.gmail.com:465
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true

          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}

          from: ${{secrets.MAIL_ADDRESS}}
          to: wevef38192@chainds.com
          subject: GitHub ${{github.job}} job of ${{github.repository}} has ${{job.status}}
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          body: ${{github.job}} job in workflow ${{github.workflow}} of ${{github.repository}} has ${{job.status}}.
